from dataclasses import dataclass
from swagger_codegen.api.client import ApiClient
from swagger_codegen.api.configuration import Configuration
from swagger_codegen.api.adapter.base import HttpClientAdapter


from .apis.trading.api import TradingApi



@dataclass
class AutogeneratedApiClient:
    configuration: Configuration
    client: ApiClient
    trading: TradingApi


def new_client(
    adapter: HttpClientAdapter, configuration: Configuration
) -> AutogeneratedApiClient:
    client = ApiClient(configuration=configuration, adapter=adapter)
    return AutogeneratedApiClient(
        configuration,
        client=client,
        
        trading=TradingApi(client, configuration)
        
    )